print('Greetings Player!')
name = input('What is your name?')
print('Hello!', name)
print('Lets begin your custom story!')
buddy = input('Choose a name for your buddy: ')
noun = input('Choose a noun: ')
place = input('Name a place: ')
adjective = input('Choose an adjective: ')
adjective2 = input('Choose another adjective: ')
noun2 = input('Choose another noun: ')
input('Your Story is ready! Press any key to read.')


print('-----------------')
print(name, 'and', buddy, 'went for a stroll' )
print('-----------------')
print('The two came  across a ', adjective, noun, '!', 'How interesting')
print('They were literally in', place, 'How fitting(?).')
print('Continuing to scroll along in', place, 'a', adjective2, 'figure could be seen in the distance') 
print('not so surprising for this place, theyre pretty common here', buddy, 'says')
print('Hm you sure seem familiar about this place',name, 'says')
print('Ha! wait till you find out about ', noun2, 'Youll poop your pants!')
